-- Creation table BCOUSFE ---------------------------------------------

create schema AVTGPMDTA;

create schema AVTMPGDTA;

create schema AVTGPMDR;

-- --------------------------------------------------------------------
-- AVTGPMDR (DEV) 
-- --------------------------------------------------------------------

-- Supression TABLE   
drop table avtgpmdr.bcousfe;

-- Création TABLE
CREATE TABLE AVTGPMDR.BCOUSFE ( 
	FECCOU DECIMAL(11, 0) NOT NULL DEFAULT 0 , 
	FEYCOU CHAR(8) NOT NULL DEFAULT '' , 
	FELNCOU CHAR(30) NOT NULL DEFAULT '' , 
	FENADH DECIMAL(6, 0) NOT NULL DEFAULT 0 , 
	FENACT DECIMAL(10, 0) NOT NULL DEFAULT 0 , 
	FELNDEST CHAR(20) NOT NULL DEFAULT '' , 
	FEUTILI CHAR(10) NOT NULL DEFAULT '' , 
	FEIMPR CHAR(10) NOT NULL DEFAULT '' , 
	FENENT DECIMAL(4, 0) NOT NULL DEFAULT 0 , 
	FENSEN DECIMAL(2, 0) NOT NULL DEFAULT 0 , 
	FENCPT DECIMAL(9, 0) NOT NULL DEFAULT 0 , 
	FEYDES CHAR(1) NOT NULL DEFAULT '' , 
	FEDCRT DATE NOT NULL DEFAULT '0001-01-01' , 
	FEDARC DATE NOT NULL DEFAULT '0001-01-01' , 
	FEHEUR TIME NOT NULL DEFAULT '00.00.00' , 
	FETRTTP CHAR(2) NOT NULL DEFAULT '' , 
	FETRTBT CHAR(2) NOT NULL DEFAULT '' , 
	FENTPA NUMERIC(9, 0) NOT NULL DEFAULT 0 , 
	FECCDI CHAR(3) NOT NULL DEFAULT '' , 
	FEREFEX CHAR(25) NOT NULL DEFAULT '' , 
	FENAGC DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	FETYPR CHAR(5) NOT NULL DEFAULT '' , 
	FESPEC CHAR(15) NOT NULL DEFAULT '' )   
; 

--delete from avtgpmdr.bcousfe;

select * from avtgpmdr.bcousfe;


-- --------------------------------------------------------------------
-- AVTGPMDTA (PROD) 
-- --------------------------------------------------------------------

-- Supression TABLE   
drop table AVTGPMDTA.BCOUSFE;

-- Création TABLE
CREATE TABLE AVTGPMDTA.BCOUSFE ( 
	FECCOU DECIMAL(11, 0) NOT NULL DEFAULT 0 , 
	FEYCOU CHAR(8) NOT NULL DEFAULT '' , 
	FELNCOU CHAR(30) NOT NULL DEFAULT '' , 
	FENADH DECIMAL(6, 0) NOT NULL DEFAULT 0 , 
	FENACT DECIMAL(10, 0) NOT NULL DEFAULT 0 , 
	FELNDEST CHAR(20) NOT NULL DEFAULT '' , 
	FEUTILI CHAR(10) NOT NULL DEFAULT '' , 
	FEIMPR CHAR(10) NOT NULL DEFAULT '' , 
	FENENT DECIMAL(4, 0) NOT NULL DEFAULT 0 , 
	FENSEN DECIMAL(2, 0) NOT NULL DEFAULT 0 , 
	FENCPT DECIMAL(9, 0) NOT NULL DEFAULT 0 , 
	FEYDES CHAR(1) NOT NULL DEFAULT '' , 
	FEDCRT DATE NOT NULL DEFAULT '0001-01-01' , 
	FEDARC DATE NOT NULL DEFAULT '0001-01-01' , 
	FEHEUR TIME NOT NULL DEFAULT '00.00.00' , 
	FETRTTP CHAR(2) NOT NULL DEFAULT '' , 
	FETRTBT CHAR(2) NOT NULL DEFAULT '' , 
	FENTPA NUMERIC(9, 0) NOT NULL DEFAULT 0 , 
	FECCDI CHAR(3) NOT NULL DEFAULT '' , 
	FEREFEX CHAR(25) NOT NULL DEFAULT '' , 
	FENAGC DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	FETYPR CHAR(5) NOT NULL DEFAULT '' , 
	FESPEC CHAR(15) NOT NULL DEFAULT '' )   
; 

-- Vérification 
select * from AVTGPMDTA.BCOUSFE where FECCOU = 25297000005; 

select * from AVTGPMDTA.bcousfe where feccou = 25293000011                    
;


select count(*) from avtgpmdta.bcousfe;

-- --------------------------------------------------------------------
-- AVTMPGDTA (RECETTE) 
-- --------------------------------------------------------------------

-- Supression TABLE   
drop table AVTMPGDTA.BCOUSFE;

-- Création TABLE
CREATE TABLE AVTMPGDTA.BCOUSFE ( 
	FECCOU DECIMAL(11, 0) NOT NULL DEFAULT 0 , 
	FEYCOU CHAR(8) NOT NULL DEFAULT '' , 
	FELNCOU CHAR(30) NOT NULL DEFAULT '' , 
	FENADH DECIMAL(6, 0) NOT NULL DEFAULT 0 , 
	FENACT DECIMAL(10, 0) NOT NULL DEFAULT 0 , 
	FELNDEST CHAR(20) NOT NULL DEFAULT '' , 
	FEUTILI CHAR(10) NOT NULL DEFAULT '' , 
	FEIMPR CHAR(10) NOT NULL DEFAULT '' , 
	FENENT DECIMAL(4, 0) NOT NULL DEFAULT 0 , 
	FENSEN DECIMAL(2, 0) NOT NULL DEFAULT 0 , 
	FENCPT DECIMAL(9, 0) NOT NULL DEFAULT 0 , 
	FEYDES CHAR(1) NOT NULL DEFAULT '' , 
	FEDCRT DATE NOT NULL DEFAULT '0001-01-01' , 
	FEDARC DATE NOT NULL DEFAULT '0001-01-01' , 
	FEHEUR TIME NOT NULL DEFAULT '00.00.00' , 
	FETRTTP CHAR(2) NOT NULL DEFAULT '' , 
	FETRTBT CHAR(2) NOT NULL DEFAULT '' , 
	FENTPA NUMERIC(9, 0) NOT NULL DEFAULT 0 , 
	FECCDI CHAR(3) NOT NULL DEFAULT '' , 
	FEREFEX CHAR(25) NOT NULL DEFAULT '' , 
	FENAGC DECIMAL(3, 0) NOT NULL DEFAULT 0 , 
	FETYPR CHAR(5) NOT NULL DEFAULT '' , 
	FESPEC CHAR(15) NOT NULL DEFAULT '' )   
; 

-- Vérification 
select * from AVTMPGDTA.BCOUSFE;

delete from avtgpmdr.bcousfe;


-- Test 
select * from AVTGPMDTAX.bcousfe;




